version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    versioning-strategy: lockfile-only
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
